# Headers
[[headers]]
for = "/*"

[headers.value]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Access-Control-Allow-Origin = "https://unisontech.org"

# Redirects[[redirects]]
from = "/schedules/latest"
to = "/schedules-latest.json"
status = 200

[[redirects]]
from = "/schedules/*"
to = "/schedules-:splat.json"
status = 200